"""Advanced transformation and behavioral grounding surfaces for Shepherd."""

from __future__ import annotations

from .chaining import (
    DEFAULT_CONFIDENCE_DECAY,
    DEFAULT_MAX_DEPTH,
    DEFAULT_MIN_CONFIDENCE,
    ChainResult,
    TransformationEngine,
    TransformationResult,
    TransformFunction,
    TransformSpec,
    calculate_chain_confidence,
    estimate_safe_depth,
)
from .grounding import (
    CoverageReport,
    EquivalenceLevel,
    EquivalenceResult,
    GroundingResult,
    Mismatch,
    TaskInputSpec,
    TestInputGenerator,
    analyze_coverage,
    behavioral_grounding,
    compare_at_level,
    compare_outcome,
    compare_relaxed,
    compare_semantic,
    compare_strict,
    generate_for_type,
    get_boundary_values,
    ground_transformation,
)
from .meta import CritiqueTask, OptimizeFromEffects, TransformTask
from .source import (
    ReconstructionError,
    ReconstructionResult,
    SourceExtractionError,
    SourceValidationError,
    extract_imports_from_file,
    extract_imports_from_source,
    extract_referenced_names,
    extract_task_imports,
    extract_task_source,
    extract_task_with_imports,
    reconstruct_task,
    reconstruct_task_class,
    try_reconstruct_task,
    try_reconstruct_task_class,
    validate_task_source,
)
from .transform_lock import (
    DEFAULT_LOCK_TIMEOUT_SECONDS,
    LockError,
    TaskTransformLock,
    TransformError,
    TransformLock,
    TransformState,
)

__all__ = [
    "DEFAULT_CONFIDENCE_DECAY",
    "DEFAULT_LOCK_TIMEOUT_SECONDS",
    "DEFAULT_MAX_DEPTH",
    "DEFAULT_MIN_CONFIDENCE",
    "ChainResult",
    "CoverageReport",
    "CritiqueTask",
    "EquivalenceLevel",
    "EquivalenceResult",
    "GroundingResult",
    "LockError",
    "Mismatch",
    "OptimizeFromEffects",
    "ReconstructionError",
    "ReconstructionResult",
    "SourceExtractionError",
    "SourceValidationError",
    "TaskInputSpec",
    "TaskTransformLock",
    "TestInputGenerator",
    "TransformError",
    "TransformFunction",
    "TransformLock",
    "TransformSpec",
    "TransformState",
    "TransformTask",
    "TransformationEngine",
    "TransformationResult",
    "analyze_coverage",
    "behavioral_grounding",
    "calculate_chain_confidence",
    "compare_at_level",
    "compare_outcome",
    "compare_relaxed",
    "compare_semantic",
    "compare_strict",
    "estimate_safe_depth",
    "extract_imports_from_file",
    "extract_imports_from_source",
    "extract_referenced_names",
    "extract_task_imports",
    "extract_task_source",
    "extract_task_with_imports",
    "generate_for_type",
    "get_boundary_values",
    "ground_transformation",
    "reconstruct_task",
    "reconstruct_task_class",
    "try_reconstruct_task",
    "try_reconstruct_task_class",
    "validate_task_source",
]
