"""Trace-first Shepherd kernel prototype."""

from typing import TYPE_CHECKING

from .kernel.canonical import (
    ABI_VERSION,
    CANONICAL_VERSION,
    ROOT_WITNESS_REF,
    ROOT_WITNESS_SCHEMA_REF,
    WITNESS_SCHEMA_REF,
    canonical_digest,
    canonical_json_bytes,
    canonical_record_input,
    canonical_witness_input,
    record_digest,
    root_witness_body,
    root_witness_body_digest,
    root_witness_record_id,
    validate_witness_body,
    witness_body_digest,
)
from .kernel.facts import (
    TRUSTED_APPEND_CONTEXT,
    TRUSTED_READ_CONTEXT,
    AppendBatch,
    AppendContext,
    AppendGroup,
    AppendLocalId,
    AppendReceipt,
    CausalClosure,
    ContextAnchor,
    Cut,
    CutId,
    CutSelector,
    CutSpec,
    ExternalAnchor,
    Fact,
    FactBody,
    FactDraft,
    FactEnvelope,
    FactId,
    FactShape,
    FactView,
    ModeFilter,
    OperationContext,
    OperationKind,
    OwnerCutoff,
    OwnerCutoffSpec,
    PathPrefix,
    ReadContext,
    Record,
    RecordBody,
    RecordDraft,
    RecordEnvelope,
    RecordId,
    RecordShape,
    RecordView,
    RetainedContext,
    RetainedContextDraft,
    TraceOwnerId,
    TraceSlice,
    TraceStore,
    VisibilityProfile,
    VisibleFact,
    VisibleRecord,
    WitnessAnchor,
    WitnessBody,
    WitnessDraft,
)
from .schemas.execution import (
    Execution,
    complete_execution_batch,
    create_execution_batch,
    execution_completed,
    execution_created,
    execution_failed,
    execution_id_for,
    execution_started,
    fail_execution_batch,
    project_execution,
    project_execution_from_store,
    project_execution_slice,
    publish_execution_frontier,
)
from .schemas.history import (
    EffectiveChild,
    EffectiveHistory,
    PublishedFact,
    project_effective_history,
    project_effective_history_from_store,
)
from .schemas.relations import (
    ExecutionRelation,
    RelationId,
    create_execution_relation_batch,
    execution_relation_created,
    execution_relation_from_fact,
    project_execution_relations,
    project_execution_relations_from_store,
    project_execution_relations_slice,
    relation_id_for,
)
from .schemas.schema_library import (
    ProjectionModeError,
    ProjectionModeRequirement,
    ProjectionSpec,
    SchemaLibrary,
    StaticSchemaLibrary,
    ensure_projection_compatible,
)

if TYPE_CHECKING:
    from .runtime import ChildHandle, Run, TaskControl, task
    from .trace_store import (
        AppendIntentConflict,
        AppendIntentConflictError,
        SQLiteTraceStore,
        TraceStoreError,
        UnknownFact,
        UnknownFactError,
    )
    from .vnext.materialization import MaterializationRequest, materialize
    from .vnext.substrates import (
        KV_PUT_CAPTURE_SCHEMA,
        KV_PUT_DECLARATION_SCHEMA,
        KV_SQLITE_SUBSTRATE_REF,
        EchoSubstrate,
        MaterializationOutcome,
        MaterializationReceipt,
        MaterializationResult,
        SQLiteKVSubstrate,
        Substrate,
        SubstrateError,
        SubstrateRegistry,
        UnknownSubstrateError,
    )

# Outer rings (runtime, vnext, trace_store) load lazily so that importing the
# kernel ring stays runtime-free: `import shepherd2.kernel.facts` executes this
# package __init__, and an eager import here would defeat the ring split
# (the retention facade — trace-identity-dual-domain.md §6). The submodule
# names themselves are also lazy attributes: the eager imports used to bind
# them as package attributes (`shepherd2.runtime`), and that surface is kept.
_LAZY_SUBMODULES = frozenset({"runtime", "vnext", "trace_store"})

_LAZY_EXPORTS = {
    "ChildHandle": "runtime",
    "Run": "runtime",
    "TaskControl": "runtime",
    "task": "runtime",
    "MaterializationRequest": "vnext.materialization",
    "materialize": "vnext.materialization",
    "EchoSubstrate": "vnext.substrates",
    "KV_PUT_CAPTURE_SCHEMA": "vnext.substrates",
    "KV_PUT_DECLARATION_SCHEMA": "vnext.substrates",
    "KV_SQLITE_SUBSTRATE_REF": "vnext.substrates",
    "MaterializationOutcome": "vnext.substrates",
    "MaterializationReceipt": "vnext.substrates",
    "MaterializationResult": "vnext.substrates",
    "SQLiteKVSubstrate": "vnext.substrates",
    "Substrate": "vnext.substrates",
    "SubstrateError": "vnext.substrates",
    "SubstrateRegistry": "vnext.substrates",
    "UnknownSubstrateError": "vnext.substrates",
    "AppendIntentConflict": "trace_store",
    "AppendIntentConflictError": "trace_store",
    "SQLiteTraceStore": "trace_store",
    "TraceStoreError": "trace_store",
    "UnknownFact": "trace_store",
    "UnknownFactError": "trace_store",
}


def __getattr__(name: str) -> object:
    from importlib import import_module

    if name in _LAZY_SUBMODULES:
        value: object = import_module(f"{__name__}.{name}")
    else:
        submodule = _LAZY_EXPORTS.get(name)
        if submodule is None:
            raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
        value = getattr(import_module(f"{__name__}.{submodule}"), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY_EXPORTS) | set(_LAZY_SUBMODULES))


__all__ = [
    "ABI_VERSION",
    "CANONICAL_VERSION",
    "KV_PUT_CAPTURE_SCHEMA",
    "KV_PUT_DECLARATION_SCHEMA",
    "KV_SQLITE_SUBSTRATE_REF",
    "ROOT_WITNESS_REF",
    "ROOT_WITNESS_SCHEMA_REF",
    "TRUSTED_APPEND_CONTEXT",
    "TRUSTED_READ_CONTEXT",
    "WITNESS_SCHEMA_REF",
    "AppendBatch",
    "AppendContext",
    "AppendGroup",
    "AppendIntentConflict",
    "AppendIntentConflictError",
    "AppendLocalId",
    "AppendReceipt",
    "CausalClosure",
    "ChildHandle",
    "ContextAnchor",
    "Cut",
    "CutId",
    "CutSelector",
    "CutSpec",
    "EchoSubstrate",
    "EffectiveChild",
    "EffectiveHistory",
    "Execution",
    "ExecutionRelation",
    "ExternalAnchor",
    "Fact",
    "FactBody",
    "FactDraft",
    "FactEnvelope",
    "FactId",
    "FactShape",
    "FactView",
    "MaterializationOutcome",
    "MaterializationReceipt",
    "MaterializationRequest",
    "MaterializationResult",
    "ModeFilter",
    "OperationContext",
    "OperationKind",
    "OwnerCutoff",
    "OwnerCutoffSpec",
    "PathPrefix",
    "ProjectionModeError",
    "ProjectionModeRequirement",
    "ProjectionSpec",
    "PublishedFact",
    "ReadContext",
    "Record",
    "RecordBody",
    "RecordDraft",
    "RecordEnvelope",
    "RecordId",
    "RecordShape",
    "RecordView",
    "RelationId",
    "RetainedContext",
    "RetainedContextDraft",
    "Run",
    "SQLiteKVSubstrate",
    "SQLiteTraceStore",
    "SchemaLibrary",
    "StaticSchemaLibrary",
    "Substrate",
    "SubstrateError",
    "SubstrateRegistry",
    "TaskControl",
    "TraceOwnerId",
    "TraceSlice",
    "TraceStore",
    "TraceStoreError",
    "UnknownFact",
    "UnknownFactError",
    "UnknownSubstrateError",
    "VisibilityProfile",
    "VisibleFact",
    "VisibleRecord",
    "WitnessAnchor",
    "WitnessBody",
    "WitnessDraft",
    "canonical_digest",
    "canonical_json_bytes",
    "canonical_record_input",
    "canonical_witness_input",
    "complete_execution_batch",
    "create_execution_batch",
    "create_execution_relation_batch",
    "ensure_projection_compatible",
    "execution_completed",
    "execution_created",
    "execution_failed",
    "execution_id_for",
    "execution_relation_created",
    "execution_relation_from_fact",
    "execution_started",
    "fail_execution_batch",
    "materialize",
    "project_effective_history",
    "project_effective_history_from_store",
    "project_execution",
    "project_execution_from_store",
    "project_execution_relations",
    "project_execution_relations_from_store",
    "project_execution_relations_slice",
    "project_execution_slice",
    "publish_execution_frontier",
    "record_digest",
    "relation_id_for",
    "root_witness_body",
    "root_witness_body_digest",
    "root_witness_record_id",
    "task",
    "validate_witness_body",
    "witness_body_digest",
]
